name: deploy astro site to nekoweb

on:
  push:
    branches: ["master"]
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  build:
    name: build site w/ astro
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install dependencies
        run: "bun install"
      - name: Build with Astro
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
        run: bun astro build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: astro-build
          path: ./dist

  deploy:
    name: deploy2nekoweb
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: astro-build
          path: dist

      - name: deploy2nekoweb
        uses: indiefellas/deploy2nekoweb@427ffdb4a6bb0e1dece1ffc8afa133a0e6f8e093
        with:
          nekoweb-api-key: ${{ secrets.NEKOWEB_API_KEY }}
          nekoweb-folder: /dist
          directory: ./dist
