name: deploy astro site to nekoweb

on:
  push:
    branches: ["master"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

env:
  BUILD_PATH: "."

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install dependencies
        run: "bun install"
        working-directory: ${{ env.BUILD_PATH }}
      - name: Build with Astro
        run: bun astro build
        working-directory: ${{ env.BUILD_PATH }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: astro-build
          path: ${{ env.BUILD_PATH }}/dist

  deploy:
    runs-on: ubuntu-latest
    name: Deploy to nekoweb
    needs: build
    steps:
      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: astro-build
      - name: deploy2nekoweb
        uses: indiefellas/deploy2nekoweb@v4
        with:
          nekoweb-api-key: ${{ secrets.NEKOWEB_API_KEY }}
          nekoweb-folder: /dist
          directory: .
              
