name: deploy astro site to nekoweb

on:
  push:
    branches: ["master"]

  workflow_dispatch:

jobs:
  test:
    name: build and deploy to nekoweb
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install dependencies
        run: "bun install"
      - name: Build with Astro
        run: bun astro build
      - name: deploy2nekoweb
        uses: indiefellas/deploy2nekoweb@v4
        with:
          nekoweb-api-key: ${{ secrets.NEKOWEB_API_KEY }}
          nekoweb-folder: /dist
          directory: ./dist
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: astro-build
          path: ./dist
              
